// Named theme presets — curated palettes the user picks from. One list
// per mode (Light/Dark). Each entry is a full TokenMap for its mode.
//
// Picking a named theme sets `ThemeConfig.themeId`; user overrides
// (accent/background/foreground/fonts) layer on top inside ThemeProvider.
//
// All entries target WCAG AA for body text. Spot-check via
// webaim.org/resources/contrastchecker/ before adding a new one.

import type { ModePalette, ResolvedMode, TokenMap } from "./types.ts";

export const DEFAULT_FONT_UI =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif';
export const DEFAULT_FONT_CODE =
  '"SF Mono", "JetBrains Mono", "Cascadia Code", "Consolas", "Liberation Mono", monospace';
export const DEFAULT_FONT_UI_SIZE = 14;
export const DEFAULT_FONT_CODE_SIZE = 13;
export const DEFAULT_CONTRAST = 50;

export type NamedTheme = {
  id: string;
  name: string;
  palette: ModePalette;
};

function light(tokens: Omit<TokenMap, "font-ui" | "font-code">): ModePalette {
  return {
    mode: "light",
    tokens: { ...tokens, "font-ui": DEFAULT_FONT_UI, "font-code": DEFAULT_FONT_CODE },
  };
}
function dark(tokens: Omit<TokenMap, "font-ui" | "font-code">): ModePalette {
  return {
    mode: "dark",
    tokens: { ...tokens, "font-ui": DEFAULT_FONT_UI, "font-code": DEFAULT_FONT_CODE },
  };
}

export const LIGHT_THEMES: readonly NamedTheme[] = [
  {
    id: "default-light",
    name: "Default",
    palette: light({
      "color-bg-base": "#f5f5f7",
      "color-bg-surface": "#ffffff",
      "color-bg-elevated": "#ffffff",
      "color-bg-hover": "#f0f0f5",
      "color-fg-default": "#1a1a1a",
      "color-fg-muted": "#6a6a75",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#0a0a0f",
      "color-accent-hover": "#2a2a55",
      "color-border-default": "#e0e0e6",
      "color-border-strong": "#d0d0d6",
      "color-danger": "#c75450",
      "color-warning": "#a37a00",
      "color-success": "#2a6a3a",
    }),
  },
  {
    id: "github-light",
    name: "GitHub",
    palette: light({
      "color-bg-base": "#ffffff",
      "color-bg-surface": "#f6f8fa",
      "color-bg-elevated": "#ffffff",
      "color-bg-hover": "#eaeef2",
      "color-fg-default": "#1f2328",
      "color-fg-muted": "#656d76",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#0969da",
      "color-accent-hover": "#218bff",
      "color-border-default": "#d0d7de",
      "color-border-strong": "#afb8c1",
      "color-danger": "#cf222e",
      "color-warning": "#9a6700",
      "color-success": "#1a7f37",
    }),
  },
  {
    id: "solarized-light",
    name: "Solarized",
    palette: light({
      "color-bg-base": "#fdf6e3",
      "color-bg-surface": "#eee8d5",
      "color-bg-elevated": "#eee8d5",
      "color-bg-hover": "#e4dec3",
      "color-fg-default": "#586e75",
      "color-fg-muted": "#93a1a1",
      "color-fg-on-accent": "#fdf6e3",
      "color-accent": "#268bd2",
      "color-accent-hover": "#4a9dd9",
      "color-border-default": "#d8d0b8",
      "color-border-strong": "#c8c0a8",
      "color-danger": "#dc322f",
      "color-warning": "#b58900",
      "color-success": "#859900",
    }),
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin",
    palette: light({
      "color-bg-base": "#eff1f5",
      "color-bg-surface": "#e6e9ef",
      "color-bg-elevated": "#dce0e8",
      "color-bg-hover": "#ccd0da",
      "color-fg-default": "#4c4f69",
      "color-fg-muted": "#6c6f85",
      "color-fg-on-accent": "#eff1f5",
      "color-accent": "#1e66f5",
      "color-accent-hover": "#3a7df7",
      "color-border-default": "#ccd0da",
      "color-border-strong": "#bcc0cc",
      "color-danger": "#d20f39",
      "color-warning": "#df8e1d",
      "color-success": "#40a02b",
    }),
  },
  {
    id: "ayu-light",
    name: "Ayu Light",
    palette: light({
      "color-bg-base": "#fcfcfc",
      "color-bg-surface": "#f8f9fa",
      "color-bg-elevated": "#fafafa",
      "color-bg-hover": "#eef0f2",
      "color-fg-default": "#5c6166",
      "color-fg-muted": "#828e9f",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#f29718",
      "color-accent-hover": "#ea9216",
      "color-border-default": "#d6d8db",
      "color-border-strong": "#b8bbbf",
      "color-danger": "#e65050",
      "color-warning": "#f29718",
      "color-success": "#6cbf43",
    }),
  },
  {
    id: "everforest-light",
    name: "Everforest Light",
    palette: light({
      "color-bg-base": "#fdf6e3",
      "color-bg-surface": "#f4f0d9",
      "color-bg-elevated": "#efebd4",
      "color-bg-hover": "#e6e2cc",
      "color-fg-default": "#5c6a72",
      "color-fg-muted": "#939f91",
      "color-fg-on-accent": "#fdf6e3",
      "color-accent": "#3a94c5",
      "color-accent-hover": "#5aaad6",
      "color-border-default": "#bdc3af",
      "color-border-strong": "#a0a997",
      "color-danger": "#f85552",
      "color-warning": "#dfa000",
      "color-success": "#8da101",
    }),
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    palette: light({
      "color-bg-base": "#fbf1c7",
      "color-bg-surface": "#ebdbb2",
      "color-bg-elevated": "#d5c4a1",
      "color-bg-hover": "#bdae93",
      "color-fg-default": "#3c3836",
      "color-fg-muted": "#7c6f64",
      "color-fg-on-accent": "#fbf1c7",
      "color-accent": "#458588",
      "color-accent-hover": "#076678",
      "color-border-default": "#a89984",
      "color-border-strong": "#928374",
      "color-danger": "#9d0006",
      "color-warning": "#b57614",
      "color-success": "#79740e",
    }),
  },
  {
    id: "linear-light",
    name: "Linear Light",
    palette: light({
      "color-bg-base": "#fbfbfb",
      "color-bg-surface": "#fbfbfb",
      "color-bg-elevated": "#f2f3f5",
      "color-bg-hover": "#e8eaee",
      "color-fg-default": "#5d6a7e",
      "color-fg-muted": "#c9ced7",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#6e79d6",
      "color-accent-hover": "#5a67d0",
      "color-border-default": "#d3d7de",
      "color-border-strong": "#b8bdc7",
      "color-danger": "#ef4343",
      "color-warning": "#b47500",
      "color-success": "#139655",
    }),
  },
  {
    id: "material-light",
    name: "Material Light",
    palette: light({
      "color-bg-base": "#fafafa",
      "color-bg-surface": "#f5f5f5",
      "color-bg-elevated": "#ffffff",
      "color-bg-hover": "#e8eaed",
      "color-fg-default": "#546e7a",
      "color-fg-muted": "#90a4ae",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#009688",
      "color-accent-hover": "#26a69a",
      "color-border-default": "#e0e0e0",
      "color-border-strong": "#bdbdbd",
      "color-danger": "#e53935",
      "color-warning": "#f57c00",
      "color-success": "#43a047",
    }),
  },
  {
    id: "night-owl-light",
    name: "Night Owl Light",
    palette: light({
      "color-bg-base": "#fbfbfb",
      "color-bg-surface": "#f0f0f0",
      "color-bg-elevated": "#f0f0f0",
      "color-bg-hover": "#d3e8f8",
      "color-fg-default": "#403f53",
      "color-fg-muted": "#90a7b2",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#2aa298",
      "color-accent-hover": "#3bbbb1",
      "color-border-default": "#d8d8d8",
      "color-border-strong": "#bbbcbf",
      "color-danger": "#e64d49",
      "color-warning": "#daaa01",
      "color-success": "#49d0c5",
    }),
  },
  {
    id: "notion-light",
    name: "Notion",
    palette: light({
      "color-bg-base": "#ffffff",
      "color-bg-surface": "#f7f6f3",
      "color-bg-elevated": "#ffffff",
      "color-bg-hover": "#efefef",
      "color-fg-default": "#37352f",
      "color-fg-muted": "#9b9a97",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#2382e2",
      "color-accent-hover": "#4097e8",
      "color-border-default": "#e9e9e7",
      "color-border-strong": "#d3d1cb",
      "color-danger": "#eb5757",
      "color-warning": "#d9730d",
      "color-success": "#0f7b6c",
    }),
  },
  {
    id: "one-light",
    name: "One Light",
    palette: light({
      "color-bg-base": "#fafafa",
      "color-bg-surface": "#eaeaeb",
      "color-bg-elevated": "#ffffff",
      "color-bg-hover": "#dbdbdc",
      "color-fg-default": "#383a42",
      "color-fg-muted": "#9d9d9f",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#526fff",
      "color-accent-hover": "#6b83ed",
      "color-border-default": "#dbdbdc",
      "color-border-strong": "#c3c3c5",
      "color-danger": "#e45649",
      "color-warning": "#c18401",
      "color-success": "#3bba54",
    }),
  },
  {
    id: "rose-pine-dawn",
    name: "Rose Pine Dawn",
    palette: light({
      "color-bg-base": "#faf4ed",
      "color-bg-surface": "#fffaf3",
      "color-bg-elevated": "#f2e9e1",
      "color-bg-hover": "#dfdad9",
      "color-fg-default": "#575279",
      "color-fg-muted": "#797593",
      "color-fg-on-accent": "#faf4ed",
      "color-accent": "#d7827e",
      "color-accent-hover": "#e09490",
      "color-border-default": "#dfdad9",
      "color-border-strong": "#cecacd",
      "color-danger": "#b4637a",
      "color-warning": "#ea9d34",
      "color-success": "#286983",
    }),
  },
  {
    id: "sentry-light",
    name: "Sentry",
    palette: light({
      "color-bg-base": "#f8f8f9",
      "color-bg-surface": "#f0f0f2",
      "color-bg-elevated": "#e6e6e9",
      "color-bg-hover": "#dad9de",
      "color-fg-default": "#181225",
      "color-fg-muted": "#6a6772",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#7553ff",
      "color-accent-hover": "#8a76ff",
      "color-border-default": "#cdccd2",
      "color-border-strong": "#b1afb8",
      "color-danger": "#d50000",
      "color-warning": "#c07500",
      "color-success": "#009800",
    }),
  },
  {
    id: "xcode-light",
    name: "Xcode",
    palette: light({
      "color-bg-base": "#ffffff",
      "color-bg-surface": "#f5f5f5",
      "color-bg-elevated": "#f5f5f5",
      "color-bg-hover": "#eef5fe",
      "color-fg-default": "#282828",
      "color-fg-muted": "#a6a6a6",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#3c93fd",
      "color-accent-hover": "#82adf3",
      "color-border-default": "#d9d7d5",
      "color-border-strong": "#bbb9b7",
      "color-danger": "#c41a16",
      "color-warning": "#643820",
      "color-success": "#007400",
    }),
  },
  // Brand-approximated families (no public design tokens) — derived from brand/known colors.
  {
    id: "absolutely-light",
    name: "Absolutely",
    palette: light({
      "color-bg-base": "#f0eee6",
      "color-bg-surface": "#f7f6f0",
      "color-bg-elevated": "#fffffb",
      "color-bg-hover": "#e7e3d6",
      "color-fg-default": "#3d3929",
      "color-fg-muted": "#6b6553",
      "color-fg-on-accent": "#2e1a0c",
      "color-accent": "#d4a27f",
      "color-accent-hover": "#c08f6a",
      "color-border-default": "#ddd8c8",
      "color-border-strong": "#cbc5b2",
      "color-danger": "#bc4334",
      "color-warning": "#9a7320",
      "color-success": "#5a7a3a",
    }),
  },
  {
    id: "proof-light",
    name: "Proof",
    palette: light({
      "color-bg-base": "#fbfaf6",
      "color-bg-surface": "#f3f1ea",
      "color-bg-elevated": "#ffffff",
      "color-bg-hover": "#ebe8de",
      "color-fg-default": "#2b2a26",
      "color-fg-muted": "#6a685e",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#3b5ba5",
      "color-accent-hover": "#4a6cb8",
      "color-border-default": "#ddd9cd",
      "color-border-strong": "#cbc7b8",
      "color-danger": "#b23a32",
      "color-warning": "#8a6a1c",
      "color-success": "#4a7a45",
    }),
  },
];

export const DARK_THEMES: readonly NamedTheme[] = [
  {
    id: "default-dark",
    name: "Default",
    palette: dark({
      "color-bg-base": "#0d1117",
      "color-bg-surface": "#161b22",
      "color-bg-elevated": "#1c2129",
      "color-bg-hover": "#21262d",
      "color-fg-default": "#e6edf3",
      "color-fg-muted": "#8d96a0",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#4a8eff",
      "color-accent-hover": "#6aa3ff",
      "color-border-default": "#30363d",
      "color-border-strong": "#484f58",
      "color-danger": "#ff6b6b",
      "color-warning": "#ffb454",
      "color-success": "#56d364",
    }),
  },
  {
    id: "dim",
    name: "Dim",
    palette: dark({
      "color-bg-base": "#22272e",
      "color-bg-surface": "#2d333b",
      "color-bg-elevated": "#373e47",
      "color-bg-hover": "#373e47",
      "color-fg-default": "#cdd9e5",
      "color-fg-muted": "#909dab",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#539bf5",
      "color-accent-hover": "#6cb6ff",
      "color-border-default": "#444c56",
      "color-border-strong": "#545d68",
      "color-danger": "#f47067",
      "color-warning": "#daa64f",
      "color-success": "#57ab5a",
    }),
  },
  {
    id: "high-contrast",
    name: "High Contrast",
    palette: dark({
      "color-bg-base": "#000000",
      "color-bg-surface": "#0a0a0a",
      "color-bg-elevated": "#141414",
      "color-bg-hover": "#1f1f1f",
      "color-fg-default": "#ffffff",
      "color-fg-muted": "#c0c0c0",
      "color-fg-on-accent": "#000000",
      "color-accent": "#5acbff",
      "color-accent-hover": "#80d8ff",
      "color-border-default": "#6a6a6a",
      "color-border-strong": "#a0a0a0",
      "color-danger": "#ff7070",
      "color-warning": "#ffd060",
      "color-success": "#70ff7c",
    }),
  },
  {
    id: "solarized-dark",
    name: "Solarized",
    palette: dark({
      "color-bg-base": "#002b36",
      "color-bg-surface": "#073642",
      "color-bg-elevated": "#0a4250",
      "color-bg-hover": "#094350",
      "color-fg-default": "#93a1a1",
      "color-fg-muted": "#657b83",
      "color-fg-on-accent": "#002b36",
      "color-accent": "#268bd2",
      "color-accent-hover": "#4a9dd9",
      "color-border-default": "#1a4f5c",
      "color-border-strong": "#2a5f6c",
      "color-danger": "#dc322f",
      "color-warning": "#b58900",
      "color-success": "#859900",
    }),
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin",
    palette: dark({
      "color-bg-base": "#1e1e2e",
      "color-bg-surface": "#181825",
      "color-bg-elevated": "#313244",
      "color-bg-hover": "#45475a",
      "color-fg-default": "#cdd6f4",
      "color-fg-muted": "#a6adc8",
      "color-fg-on-accent": "#1e1e2e",
      "color-accent": "#cba6f7",
      "color-accent-hover": "#dbb8ff",
      "color-border-default": "#45475a",
      "color-border-strong": "#585b70",
      "color-danger": "#f38ba8",
      "color-warning": "#f9e2af",
      "color-success": "#a6e3a1",
    }),
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    palette: dark({
      "color-bg-base": "#1a1b26",
      "color-bg-surface": "#24283b",
      "color-bg-elevated": "#2e3146",
      "color-bg-hover": "#2e3146",
      "color-fg-default": "#c0caf5",
      "color-fg-muted": "#565f89",
      "color-fg-on-accent": "#1a1b26",
      "color-accent": "#7aa2f7",
      "color-accent-hover": "#92b4ff",
      "color-border-default": "#2e3146",
      "color-border-strong": "#3b3e58",
      "color-danger": "#f7768e",
      "color-warning": "#e0af68",
      "color-success": "#9ece6a",
    }),
  },
  {
    id: "dracula",
    name: "Dracula",
    palette: dark({
      "color-bg-base": "#282a36",
      "color-bg-surface": "#2e3140",
      "color-bg-elevated": "#44475a",
      "color-bg-hover": "#44475a",
      "color-fg-default": "#f8f8f2",
      "color-fg-muted": "#6272a4",
      "color-fg-on-accent": "#282a36",
      "color-accent": "#bd93f9",
      "color-accent-hover": "#d6b0ff",
      "color-border-default": "#44475a",
      "color-border-strong": "#5b5e75",
      "color-danger": "#ff5555",
      "color-warning": "#f1fa8c",
      "color-success": "#50fa7b",
    }),
  },
  {
    id: "monokai",
    name: "Monokai",
    palette: dark({
      "color-bg-base": "#272822",
      "color-bg-surface": "#3e3d32",
      "color-bg-elevated": "#49483e",
      "color-bg-hover": "#49483e",
      "color-fg-default": "#f8f8f2",
      "color-fg-muted": "#a59f85",
      "color-fg-on-accent": "#272822",
      "color-accent": "#f92672",
      "color-accent-hover": "#fb4288",
      "color-border-default": "#49483e",
      "color-border-strong": "#5c5b50",
      "color-danger": "#f92672",
      "color-warning": "#fd971f",
      "color-success": "#a6e22e",
    }),
  },
  {
    id: "ayu-dark",
    name: "Ayu Dark",
    palette: dark({
      "color-bg-base": "#10141c",
      "color-bg-surface": "#0d1017",
      "color-bg-elevated": "#141821",
      "color-bg-hover": "#1d2433",
      "color-fg-default": "#bfbdb6",
      "color-fg-muted": "#5a6378",
      "color-fg-on-accent": "#0d1017",
      "color-accent": "#e6b450",
      "color-accent-hover": "#deae4d",
      "color-border-default": "#1b1f29",
      "color-border-strong": "#2a3040",
      "color-danger": "#d95757",
      "color-warning": "#e6b450",
      "color-success": "#70bf56",
    }),
  },
  {
    id: "ayu-mirage",
    name: "Ayu Mirage",
    palette: dark({
      "color-bg-base": "#242936",
      "color-bg-surface": "#1f2430",
      "color-bg-elevated": "#282e3b",
      "color-bg-hover": "#343a48",
      "color-fg-default": "#cccac2",
      "color-fg-muted": "#707a8c",
      "color-fg-on-accent": "#1f2430",
      "color-accent": "#ffcc66",
      "color-accent-hover": "#f9c55d",
      "color-border-default": "#171b24",
      "color-border-strong": "#2a2f3d",
      "color-danger": "#ff6666",
      "color-warning": "#ffcc66",
      "color-success": "#87d96c",
    }),
  },
  {
    id: "everforest-dark",
    name: "Everforest Dark",
    palette: dark({
      "color-bg-base": "#2d353b",
      "color-bg-surface": "#232a2e",
      "color-bg-elevated": "#343f44",
      "color-bg-hover": "#3d484d",
      "color-fg-default": "#d3c6aa",
      "color-fg-muted": "#859289",
      "color-fg-on-accent": "#2d353b",
      "color-accent": "#7fbbb3",
      "color-accent-hover": "#95cac2",
      "color-border-default": "#475258",
      "color-border-strong": "#4f585e",
      "color-danger": "#e67e80",
      "color-warning": "#dbbc7f",
      "color-success": "#a7c080",
    }),
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    palette: dark({
      "color-bg-base": "#282828",
      "color-bg-surface": "#1d2021",
      "color-bg-elevated": "#3c3836",
      "color-bg-hover": "#504945",
      "color-fg-default": "#ebdbb2",
      "color-fg-muted": "#928374",
      "color-fg-on-accent": "#282828",
      "color-accent": "#83a598",
      "color-accent-hover": "#9db8ae",
      "color-border-default": "#504945",
      "color-border-strong": "#665c54",
      "color-danger": "#fb4934",
      "color-warning": "#fabd2f",
      "color-success": "#b8bb26",
    }),
  },
  {
    id: "linear-dark",
    name: "Linear Dark",
    palette: dark({
      "color-bg-base": "#1f2023",
      "color-bg-surface": "#1f2023",
      "color-bg-elevated": "#292a2e",
      "color-bg-hover": "#323439",
      "color-fg-default": "#c1c3c8",
      "color-fg-muted": "#4f5259",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#5e6ad2",
      "color-accent-hover": "#727ee6",
      "color-border-default": "#46484e",
      "color-border-strong": "#5c5e65",
      "color-danger": "#eb5757",
      "color-warning": "#ffcc6d",
      "color-success": "#4cb782",
    }),
  },
  {
    id: "material-dark",
    name: "Material Dark",
    palette: dark({
      "color-bg-base": "#212121",
      "color-bg-surface": "#1a1a1a",
      "color-bg-elevated": "#2c2c2c",
      "color-bg-hover": "#303030",
      "color-fg-default": "#eeffff",
      "color-fg-muted": "#848484",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#009688",
      "color-accent-hover": "#26a69a",
      "color-border-default": "#3a3a3a",
      "color-border-strong": "#4a4a4a",
      "color-danger": "#f07178",
      "color-warning": "#ffcb6b",
      "color-success": "#c3e88d",
    }),
  },
  {
    id: "night-owl",
    name: "Night Owl",
    palette: dark({
      "color-bg-base": "#011627",
      "color-bg-surface": "#011627",
      "color-bg-elevated": "#0b253a",
      "color-bg-hover": "#1d3b53",
      "color-fg-default": "#d6deeb",
      "color-fg-muted": "#637777",
      "color-fg-on-accent": "#011627",
      "color-accent": "#7e57c2",
      "color-accent-hover": "#9575cd",
      "color-border-default": "#122d42",
      "color-border-strong": "#1e3d54",
      "color-danger": "#ef5350",
      "color-warning": "#b39554",
      "color-success": "#9ccc65",
    }),
  },
  {
    id: "nord",
    name: "Nord",
    palette: dark({
      "color-bg-base": "#2e3440",
      "color-bg-surface": "#2e3440",
      "color-bg-elevated": "#3b4252",
      "color-bg-hover": "#434c5e",
      "color-fg-default": "#eceff4",
      "color-fg-muted": "#4c566a",
      "color-fg-on-accent": "#2e3440",
      "color-accent": "#88c0d0",
      "color-accent-hover": "#8fbcbb",
      "color-border-default": "#434c5e",
      "color-border-strong": "#4c566a",
      "color-danger": "#bf616a",
      "color-warning": "#ebcb8b",
      "color-success": "#a3be8c",
    }),
  },
  {
    id: "notion-dark",
    name: "Notion Dark",
    palette: dark({
      "color-bg-base": "#191919",
      "color-bg-surface": "#2f3438",
      "color-bg-elevated": "#373c3f",
      "color-bg-hover": "#3f4448",
      "color-fg-default": "#e9e9e7",
      "color-fg-muted": "#9b9a97",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#2382e2",
      "color-accent-hover": "#4097e8",
      "color-border-default": "#373c3f",
      "color-border-strong": "#4a4f52",
      "color-danger": "#eb5757",
      "color-warning": "#d9730d",
      "color-success": "#0f9960",
    }),
  },
  {
    id: "one-dark",
    name: "One Dark",
    palette: dark({
      "color-bg-base": "#282c34",
      "color-bg-surface": "#21252b",
      "color-bg-elevated": "#21252b",
      "color-bg-hover": "#2c313a",
      "color-fg-default": "#abb2bf",
      "color-fg-muted": "#495162",
      "color-fg-on-accent": "#282c34",
      "color-accent": "#61afef",
      "color-accent-hover": "#7ec2f5",
      "color-border-default": "#3e4452",
      "color-border-strong": "#545d68",
      "color-danger": "#e06c75",
      "color-warning": "#e5c07b",
      "color-success": "#98c379",
    }),
  },
  {
    id: "rose-pine",
    name: "Rose Pine",
    palette: dark({
      "color-bg-base": "#191724",
      "color-bg-surface": "#191724",
      "color-bg-elevated": "#1f1d2e",
      "color-bg-hover": "#26233a",
      "color-fg-default": "#e0def4",
      "color-fg-muted": "#908caa",
      "color-fg-on-accent": "#191724",
      "color-accent": "#ebbcba",
      "color-accent-hover": "#f2c9c7",
      "color-border-default": "#26233a",
      "color-border-strong": "#403d52",
      "color-danger": "#eb6f92",
      "color-warning": "#f6c177",
      "color-success": "#31748f",
    }),
  },
  {
    id: "sentry-dark",
    name: "Sentry Dark",
    palette: dark({
      "color-bg-base": "#181225",
      "color-bg-surface": "#1b1821",
      "color-bg-elevated": "#24202b",
      "color-bg-hover": "#2e2936",
      "color-fg-default": "#f9f8f9",
      "color-fg-muted": "#6a6772",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#7553ff",
      "color-accent-hover": "#8a76ff",
      "color-border-default": "#393442",
      "color-border-strong": "#4c4954",
      "color-danger": "#ff002b",
      "color-warning": "#fdb81b",
      "color-success": "#00a71a",
    }),
  },
  {
    id: "vercel-dark",
    name: "Vercel",
    palette: dark({
      "color-bg-base": "#000000",
      "color-bg-surface": "#0a0a0a",
      "color-bg-elevated": "#111111",
      "color-bg-hover": "#1a1a1a",
      "color-fg-default": "#ededed",
      "color-fg-muted": "#454d54",
      "color-fg-on-accent": "#000000",
      "color-accent": "#0070f3",
      "color-accent-hover": "#338ef7",
      "color-border-default": "#333333",
      "color-border-strong": "#555555",
      "color-danger": "#e61f44",
      "color-warning": "#f5a623",
      "color-success": "#62c073",
    }),
  },
  {
    id: "xcode-dark",
    name: "Xcode Dark",
    palette: dark({
      "color-bg-base": "#292a30",
      "color-bg-surface": "#252629",
      "color-bg-elevated": "#1c1d20",
      "color-bg-hover": "#2f3239",
      "color-fg-default": "#dfdfe0",
      "color-fg-muted": "#747478",
      "color-fg-on-accent": "#ffffff",
      "color-accent": "#3c93fd",
      "color-accent-hover": "#82adf3",
      "color-border-default": "#16171a",
      "color-border-strong": "#2a2b2e",
      "color-danger": "#e21514",
      "color-warning": "#f5c443",
      "color-success": "#00a600",
    }),
  },
  // Brand-approximated families (no public design tokens) — derived from brand/known colors.
  {
    id: "raycast-dark",
    name: "Raycast",
    palette: dark({
      "color-bg-base": "#0f0f12",
      "color-bg-surface": "#17171b",
      "color-bg-elevated": "#1d1d22",
      "color-bg-hover": "#26262d",
      "color-fg-default": "#ececf0",
      "color-fg-muted": "#9b9ba6",
      "color-fg-on-accent": "#2b0d0d",
      "color-accent": "#ff6363",
      "color-accent-hover": "#ff7d7d",
      "color-border-default": "#2a2a31",
      "color-border-strong": "#3a3a42",
      "color-danger": "#ff6b6b",
      "color-warning": "#e0a44a",
      "color-success": "#3fb950",
    }),
  },
  {
    id: "codex-dark",
    name: "Codex",
    palette: dark({
      "color-bg-base": "#0e1110",
      "color-bg-surface": "#161a18",
      "color-bg-elevated": "#1c211e",
      "color-bg-hover": "#252b27",
      "color-fg-default": "#e6ece9",
      "color-fg-muted": "#93a09a",
      "color-fg-on-accent": "#03110c",
      "color-accent": "#10a37f",
      "color-accent-hover": "#1abc94",
      "color-border-default": "#283330",
      "color-border-strong": "#384741",
      "color-danger": "#f1707b",
      "color-warning": "#d8a657",
      "color-success": "#2ea043",
    }),
  },
  {
    id: "lobster-dark",
    name: "Lobster",
    palette: dark({
      "color-bg-base": "#161210",
      "color-bg-surface": "#1e1916",
      "color-bg-elevated": "#251f1b",
      "color-bg-hover": "#2f2823",
      "color-fg-default": "#f0e7e2",
      "color-fg-muted": "#ab9d96",
      "color-fg-on-accent": "#2a0c06",
      "color-accent": "#e8503a",
      "color-accent-hover": "#f26a55",
      "color-border-default": "#332a25",
      "color-border-strong": "#453932",
      "color-danger": "#e8503a",
      "color-warning": "#d6943f",
      "color-success": "#6fae5f",
    }),
  },
  {
    id: "oscurange-dark",
    name: "Oscurange",
    palette: dark({
      "color-bg-base": "#121110",
      "color-bg-surface": "#1a1916",
      "color-bg-elevated": "#201e1b",
      "color-bg-hover": "#2a2722",
      "color-fg-default": "#ededea",
      "color-fg-muted": "#a09c95",
      "color-fg-on-accent": "#2a1500",
      "color-accent": "#ff8c42",
      "color-accent-hover": "#ffa05f",
      "color-border-default": "#2e2b26",
      "color-border-strong": "#403c35",
      "color-danger": "#ff6b5e",
      "color-warning": "#ffb454",
      "color-success": "#84c46b",
    }),
  },
  {
    id: "temple-dark",
    name: "Temple",
    palette: dark({
      "color-bg-base": "#14130f",
      "color-bg-surface": "#1c1a15",
      "color-bg-elevated": "#22201a",
      "color-bg-hover": "#2c2920",
      "color-fg-default": "#ece8dd",
      "color-fg-muted": "#a39e8c",
      "color-fg-on-accent": "#1a1604",
      "color-accent": "#c9a227",
      "color-accent-hover": "#ddb53a",
      "color-border-default": "#2e2a20",
      "color-border-strong": "#413c2e",
      "color-danger": "#cf6a52",
      "color-warning": "#c9a227",
      "color-success": "#8a9a4b",
    }),
  },
];

// Convenience aliases for the historical names.
export const LIGHT_PALETTE: ModePalette = LIGHT_THEMES[0].palette;
export const DARK_PALETTE: ModePalette = DARK_THEMES[0].palette;

export function namedThemesFor(mode: ResolvedMode): readonly NamedTheme[] {
  return mode === "dark" ? DARK_THEMES : LIGHT_THEMES;
}

export function findNamedTheme(mode: ResolvedMode, id: string | undefined): NamedTheme {
  const list = namedThemesFor(mode);
  if (id) {
    const found = list.find((t) => t.id === id);
    if (found) return found;
  }
  return list[0];
}

export function paletteFor(mode: ResolvedMode): ModePalette {
  return mode === "dark" ? DARK_PALETTE : LIGHT_PALETTE;
}

/**
 * Suggested font stacks for datalist-style auto-complete. Not a hard
 * allowlist — users can type any CSS font-family stack.
 */
export const FONT_SUGGESTIONS = {
  ui: [
    { name: "System", value: DEFAULT_FONT_UI },
    { name: "Inter", value: '"Inter", system-ui, sans-serif' },
    { name: "IBM Plex Sans", value: '"IBM Plex Sans", system-ui, sans-serif' },
    { name: "Georgia", value: 'Georgia, "Times New Roman", serif' },
  ],
  code: [
    { name: "System Mono", value: DEFAULT_FONT_CODE },
    { name: "JetBrains Mono", value: '"JetBrains Mono", monospace' },
    { name: "Fira Code", value: '"Fira Code", monospace' },
    { name: "IBM Plex Mono", value: '"IBM Plex Mono", monospace' },
  ],
} as const;
